format = '''\[$username@$hostname $directory\] $character'''

add_newline = false

[git_branch]
style = "bold green"
format = "[\\[[$branch$tag](bold green)\\]](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
truncation_length = 8
truncation_symbol = '.../'
disabled = false
style = 'cyan'

[username]
show_always = true
format = '[$user]($style)'
disabled = false
style_user = 'purple'

[hostname]
disabled = false
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
style = "white"

[character] # The name of the module we are configuring is 'character'
success_symbol = '[≵](bold green)'
error_symbol = '[≵](bold red)'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "


